create database shift_allocation;
use shift_allocation;
create table hr_manager(
	id integer primary key,
    pass varchar(50),
    name varchar(50)
    );
create table employee(
	e_id integer primary key,
    e_name varchar(50),
    no_of_hours_worked integer,
    designation varchar(50),
    e_gmail varchar(100)
    );
insert into employee values
(1, 'John Doe', 34, 'Cashier', 'john.doe@yahoo.com'),
(2, 'Jane Smith', 28, 'Cashier', 'jane.smith@yahoo.com'),
(3, 'Mark Lee', 30, 'Cashier', 'mark.lee@yahoo.com'),
(4, 'Anna White', 35, 'Cashier', 'anna.white@yahoo.com'),
(5, 'Chris Green', 32, 'Cashier', 'chris.green@yahoo.com'),
(6, 'Sarah Black', 29, 'Cashier', 'sarah.black@yahoo.com'),
(7, 'Tom Brown', 31, 'Cashier', 'tom.brown@yahoo.com'),
(8, 'Emily Clark', 33, 'Cashier', 'emily.clark@yahoo.com'),
(9, 'Daniel King', 30, 'Cashier', 'daniel.king@yahoo.com'),
(10, 'Laura Scott', 27, 'Cashier', 'laura.scott@yahoo.com'),
(11, 'Jack Hill', 34, 'Cashier', 'jack.hill@yahoo.com'),
(12, 'Olivia Adams', 29, 'Cashier', 'olivia.adams@yahoo.com'),
(13, 'Liam Turner', 28, 'Cashier', 'liam.turner@yahoo.com'),
(14, 'Sophia Evans', 31, 'Cashier', 'sophia.evans@yahoo.com'),
(15, 'Mason Hall', 32, 'Cashier', 'mason.hall@yahoo.com'),
(16, 'Ella Ward', 27, 'Cashier', 'ella.ward@yahoo.com'),
(17, 'Jacob Carter', 30, 'Cashier', 'jacob.carter@yahoo.com'),
(18, 'Ava Mitchell', 35, 'Cashier', 'ava.mitchell@yahoo.com'),
(19, 'Michael Brooks', 29, 'Cashier', 'michael.brooks@yahoo.com'),
(20, 'Grace Lewis', 28, 'Cashier', 'grace.lewis@yahoo.com'),
(21, 'Alice Johnson', 30, 'Supervisor', 'alice.johnson@gmail.com'),
(22, 'Bob Smith', 28, 'Supervisor', 'bob.smith@gmail.com'),
(23, 'Charlie Davis', 32, 'Supervisor', 'charlie.davis@gmail.com'),
(24, 'Diana Clark', 34, 'Supervisor', 'diana.clark@gmail.com'),
(25, 'Ethan Brown', 29, 'Supervisor', 'ethan.brown@gmail.com'),
(26, 'Fiona Adams', 27, 'Supervisor', 'fiona.adams@gmail.com'),
(27, 'George Miller', 31, 'Supervisor', 'george.miller@gmail.com'),
(28, 'Hannah White', 25, 'Supervisor', 'hannah.white@gmail.com'),
(29, 'Isaac Wilson', 33, 'Supervisor', 'isaac.wilson@gmail.com'),
(30, 'Julia Thomas', 22, 'Supervisor', 'julia.thomas@gmail.com'),
(31, 'Kevin Moore', 35, 'Supervisor', 'kevin.moore@gmail.com'),
(32, 'Liam Taylor', 26, 'Supervisor', 'liam.taylor@gmail.com'),
(33, 'Mia Scott', 20, 'Supervisor', 'mia.scott@gmail.com'),
(34, 'Nathan Harris', 24, 'Supervisor', 'nathan.harris@gmail.com'),
(35, 'Olivia Martinez', 18, 'Supervisor', 'olivia.martinez@gmail.com'),
(36, 'Peter Robinson', 23, 'Supervisor', 'peter.robinson@gmail.com'),
(37, 'Quinn Lewis', 19, 'Supervisor', 'quinn.lewis@gmail.com'),
(38, 'Rachel Walker', 21, 'Supervisor', 'rachel.walker@gmail.com'),
(39, 'Samuel Allen', 30, 'Supervisor', 'samuel.allen@gmail.com'),
(40, 'Tina Young', 28, 'Supervisor', 'tina.young@gmail.com'),
(41, 'John Doe', 25, 'Inventory Manager', 'john.doe@hotmail.com'),
(42, 'Jane Smith', 27, 'Inventory Manager', 'jane.smith@hotmail.com'),
(43, 'Mike Johnson', 23, 'Inventory Manager', 'mike.johnson@hotmail.com'),
(44, 'Emily Davis', 20, 'Inventory Manager', 'emily.davis@hotmail.com'),
(45, 'Chris Wilson', 26, 'Inventory Manager', 'chris.wilson@hotmail.com'),
(46, 'Sarah Brown', 24, 'Inventory Manager', 'sarah.brown@hotmail.com'),
(47, 'David Martinez', 22, 'Inventory Manager', 'david.martinez@hotmail.com'),
(48, 'Anna Taylor', 28, 'Inventory Manager', 'anna.taylor@hotmail.com'),
(49, 'James Anderson', 19, 'Inventory Manager', 'james.anderson@hotmail.com'),
(50, 'Laura Thomas', 21, 'Inventory Manager', 'laura.thomas@hotmail.com'),
(51, 'Robert White', 18, 'Inventory Manager', 'robert.white@hotmail.com'),
(52, 'Patricia Harris', 27, 'Inventory Manager', 'patricia.harris@hotmail.com'),
(53, 'Linda Clark', 25, 'Inventory Manager', 'linda.clark@hotmail.com'),
(54, 'Steven Lewis', 22, 'Inventory Manager', 'steven.lewis@hotmail.com'),
(55, 'Jessica Walker', 23, 'Inventory Manager', 'jessica.walker@hotmail.com'),
(56, 'Matthew Hall', 24, 'Inventory Manager', 'matthew.hall@hotmail.com'),
(57, 'Olivia Allen', 20, 'Inventory Manager', 'olivia.allen@hotmail.com'),
(58, 'Daniel Young', 26, 'Inventory Manager', 'daniel.young@hotmail.com'),
(59, 'Sophia King', 21, 'Inventory Manager', 'sophia.king@hotmail.com'),
(60, 'Brian Wright', 19, 'Inventory Manager', 'brian.wright@hotmail.com'),
(61, 'Karen Scott', 28, 'Inventory Manager', 'karen.scott@hotmail.com'),
(62, 'Jason Green', 23, 'Inventory Manager', 'jason.green@hotmail.com'),
(63, 'Nancy Adams', 22, 'Inventory Manager', 'nancy.adams@hotmail.com'),
(64, 'Paul Baker', 25, 'Inventory Manager', 'paul.baker@hotmail.com'),
(65, 'Rebecca Gonzalez', 26, 'Inventory Manager', 'rebecca.gonzalez@hotmail.com'),
(66, 'Alice Johnson', 38, 'Customer Help', 'alice.johnson@gmail.com'),
(67, 'Bob Smith', 39, 'Customer Help', 'bob.smith@gmail.com'),
(68, 'Charlie Davis', 35, 'Customer Help', 'charlie.davis@gmail.com'),
(69, 'David Lee', 40, 'Customer Help', 'david.lee@gmail.com'),
(70, 'Eva Brown', 36, 'Customer Help', 'eva.brown@gmail.com'),
(71, 'Fiona Williams', 37, 'Customer Help', 'fiona.williams@gmail.com'),
(72, 'George Taylor', 39, 'Customer Help', 'george.taylor@gmail.com'),
(73, 'Hannah Martinez', 34, 'Customer Help', 'hannah.martinez@gmail.com'),
(74, 'Ivy Moore', 33, 'Customer Help', 'ivy.moore@gmail.com'),
(75, 'Jack Anderson', 32, 'Customer Help', 'jack.anderson@gmail.com'),
(76, 'Karen Thomas', 30, 'Customer Help', 'karen.thomas@gmail.com'),
(77, 'Leo Jackson', 38, 'Customer Help', 'leo.jackson@gmail.com'),
(78, 'Mia White', 31, 'Customer Help', 'mia.white@gmail.com'),
(79, 'Nathan Harris', 36, 'Customer Help', 'nathan.harris@gmail.com'),
(80, 'Olivia Clark', 35, 'Customer Help', 'olivia.clark@gmail.com'),
(81, 'Paul Lewis', 40, 'Customer Help', 'paul.lewis@gmail.com'),
(82, 'Quinn Walker', 37, 'Customer Help', 'quinn.walker@gmail.com'),
(83, 'Rachel Hall', 33, 'Customer Help', 'rachel.hall@gmail.com'),
(84, 'Samuel Allen', 31, 'Customer Help', 'samuel.allen@gmail.com'),
(85, 'Tina Young', 32, 'Customer Help', 'tina.young@gmail.com'),
(86, 'Ursula King', 30, 'Customer Help', 'ursula.king@gmail.com'),
(87, 'Victor Scott', 29, 'Customer Help', 'victor.scott@gmail.com'),
(88, 'Wendy Green', 34, 'Customer Help', 'wendy.green@gmail.com'),
(89, 'Xander Adams', 39, 'Customer Help', 'xander.adams@gmail.com'),
(90, 'Yara Nelson', 40, 'Customer Help', 'yara.nelson@gmail.com'),
(91, 'John Doe', 18, 'Cleaning Staff', 'john.doe@yahoo.com'),
(92, 'Jane Smith', 15, 'Cleaning Staff', 'jane.smith@yahoo.com'),
(93, 'Chris Brown', 19, 'Cleaning Staff', 'chris.brown@yahoo.com'),
(94, 'Sarah Johnson', 17, 'Cleaning Staff', 'sarah.johnson@yahoo.com'),
(95, 'Michael White', 20, 'Cleaning Staff', 'michael.white@yahoo.com'),
(96, 'Emily Davis', 14, 'Cleaning Staff', 'emily.davis@yahoo.com'),
(97, 'David Clark', 12, 'Cleaning Staff', 'david.clark@yahoo.com'),
(98, 'Olivia Lewis', 16, 'Cleaning Staff', 'olivia.lewis@yahoo.com'),
(99, 'James Harris', 13, 'Cleaning Staff', 'james.harris@yahoo.com'),
(100, 'Sophia Walker', 10, 'Cleaning Staff', 'sophia.walker@yahoo.com'),
(101, 'Benjamin Hall', 19, 'Cleaning Staff', 'benjamin.hall@yahoo.com'),
(102, 'Mia Allen', 15, 'Cleaning Staff', 'mia.allen@yahoo.com'),
(103, 'Ethan Young', 11, 'Cleaning Staff', 'ethan.young@yahoo.com'),
(104, 'Isabella King', 18, 'Cleaning Staff', 'isabella.king@yahoo.com'),
(105, 'Matthew Scott', 14, 'Cleaning Staff', 'matthew.scott@yahoo.com'),
(106, 'John Smith', 25, 'Manager', 'john.smith@example.com'),
(107, 'Alice Brown', 22, 'Manager', 'alice.brown@example.com'),
(108, 'Bob Johnson', 18, 'Manager', 'bob.johnson@example.com'),
(109, 'Carol White', 20, 'Manager', 'carol.white@example.com'),
(110, 'David Green', 27, 'Manager', 'david.green@example.com'),
(111, 'Eva Adams', 23, 'Manager', 'eva.adams@example.com'),
(112, 'Frank Lee', 26, 'Manager', 'frank.lee@example.com'),
(113, 'Grace Miller', 21, 'Manager', 'grace.miller@example.com'),
(114, 'Harry Clark', 19, 'Manager', 'harry.clark@example.com'),
(115, 'Ivy Scott', 24, 'Manager', 'ivy.scott@example.com'),
(116, 'Jack Walker', 22, 'Manager', 'jack.walker@example.com'),
(117, 'Kathy Hall', 17, 'Manager', 'kathy.hall@example.com'),
(118, 'Liam Allen', 25, 'Manager', 'liam.allen@example.com'),
(119, 'Mona Perez', 23, 'Manager', 'mona.perez@example.com'),
(120, 'Nathan Young', 26, 'Manager', 'nathan.young@example.com');
create table shift(
	shift_id integer primary key,
    shift_duration integer,
    shift_timing varchar(50),
    shift_day varchar(50),
    shift_priority integer
    );
INSERT INTO shift VALUES 
(1, 3, 'M1', 'Day1', 1),
(2, 3, 'D2', 'Day1', 2),
(3, 3, 'D2', 'Day1', 3),
(4, 3, 'E1', 'Day1', 1),
(5, 3, 'N1', 'Day1', 1),
(6, 3, 'M1', 'Day2', 1),
(7, 3, 'D2', 'Day2', 2),
(8, 3, 'D2', 'Day2', 3),
(9, 3, 'E1', 'Day2', 1),
(10, 3, 'N1', 'Day2', 1),
(11, 3, 'M1', 'Day3', 1),
(12, 3, 'D2', 'Day3', 2),
(13, 3, 'D2', 'Day3', 3),
(14, 3, 'E1', 'Day3', 1),
(15, 3, 'N1', 'Day3', 1),
(16, 3, 'M1', 'Day4', 1),
(17, 3, 'D2', 'Day4', 2),
(18, 3, 'D2', 'Day4', 3),
(19, 3, 'E1', 'Day4', 1),
(20, 3, 'N1', 'Day4', 1),
(21, 3, 'M1', 'Day5', 1),
(22, 3, 'D2', 'Day5', 2),
(23, 3, 'D2', 'Day5', 3),
(24, 3, 'E1', 'Day5', 1),
(25, 3, 'N1', 'Day5', 1),
(26, 3, 'M1', 'Day6', 1),
(27, 3, 'D2', 'Day6', 2),
(28, 3, 'D2', 'Day6', 3),
(29, 3, 'E1', 'Day6', 1),
(30, 3, 'N1', 'Day6', 1),
(31, 3, 'M1', 'Day7', 1),
(32, 3, 'D2', 'Day7', 2),
(33, 3, 'D2', 'Day7', 3),
(34, 3, 'E1', 'Day7', 1),
(35, 3, 'N1', 'Day7', 1);
